language: android

android:
  components:
    - build-tools-29.0.2
    - android-29

jobs:
  include:
    - stage: build
      script:
        - ./gradlew assembleRelease
    - stage: deploy
    deploy:
      - provider: releases
        skip_cleanup: true
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        on:
          branch: master
          tags: true
      - provider: releases
        skip_cleanup: true
        file: app/build/outputs/apk/release/app-release-unsigned.apk
        prerelease: true
        on:
          branch: prerelease
          tags: true
